version: '3.7'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_USER: testuser
      MYSQL_DATABASE: demo_database
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_pass

    secrets:
      - db_root_pass

secrets:
  db_root_pass:
    external: true