version: "3.7"

services:
  basic-auth:
    image: registry
    build:
      context: ./auth/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: basic-realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
